import { api, unwrap } from "./api";

export const financeApi = {
  accounts: (includeInactive = false) => unwrap(api.get(`/api/accounts${includeInactive ? "?include_inactive=1" : ""}`)),
  createAccount: (p: object) => unwrap(api.post("/api/accounts", p)),
  updateAccount: (id: number, p: object) => unwrap(api.patch(`/api/accounts/${id}`, p)),
  categories: (kind?: string) => unwrap(api.get(`/api/categories${kind ? `?kind=${kind}` : ""}`)),
  createCategory: (p: object) => unwrap(api.post("/api/categories", p)),
  updateCategory: (id: number, p: object) => unwrap(api.patch(`/api/categories/${id}`, p)),
  deleteCategory: (id: number) => unwrap(api.delete(`/api/categories/${id}`)),
  transactions: (params: Record<string, string | number | undefined>) =>
    unwrap(api.get("/api/transactions", { params })),
  createTx: (p: object) => unwrap(api.post("/api/transactions", p)),
  updateTx: (id: number, p: object) => unwrap(api.patch(`/api/transactions/${id}`, p)),
  deleteTx: (id: number) => unwrap(api.delete(`/api/transactions/${id}`)),
  duplicateTx: (id: number) => unwrap(api.post(`/api/transactions/${id}/duplicate`)),
  getTx: (id: number) => unwrap(api.get(`/api/transactions/${id}`)),
  parseQuick: (text: string) => unwrap(api.post("/api/transactions/quick-parse", { text })),
  dashboard: (period: string) => unwrap(api.get(`/api/dashboard?period=${period}`)),
  budgets: (month?: string) => unwrap(api.get(`/api/budgets${month ? `?month=${month}` : ""}`)),
  saveBudget: (p: object) => unwrap(api.put("/api/budgets", p)),
  copyBudget: (month: string) => unwrap(api.post("/api/budgets/copy-previous", { month })),
  budgetHistory: () => unwrap(api.get("/api/budgets/history")),
  goals: () => unwrap(api.get("/api/goals")),
  createGoal: (p: object) => unwrap(api.post("/api/goals", p)),
  updateGoal: (id: number, p: object) => unwrap(api.patch(`/api/goals/${id}`, p)),
  deleteGoal: (id: number) => unwrap(api.delete(`/api/goals/${id}`)),
  depositGoal: (id: number, p: object) => unwrap(api.post(`/api/goals/${id}/deposit`, p)),
  withdrawGoal: (id: number, p: object) => unwrap(api.post(`/api/goals/${id}/withdraw`, p)),
  goalHistory: (id: number) => unwrap(api.get(`/api/goals/${id}/history`)),
  recurring: () => unwrap(api.get("/api/recurring")),
  createRecurring: (p: object) => unwrap(api.post("/api/recurring", p)),
  updateRecurring: (id: number, p: object) => unwrap(api.patch(`/api/recurring/${id}`, p)),
  deleteRecurring: (id: number) => unwrap(api.delete(`/api/recurring/${id}`)),
  bills: () => unwrap(api.get("/api/bills")),
  createBill: (p: object) => unwrap(api.post("/api/bills", p)),
  updateBill: (id: number, p: object) => unwrap(api.patch(`/api/bills/${id}`, p)),
  deleteBill: (id: number) => unwrap(api.delete(`/api/bills/${id}`)),
  subscriptions: () => unwrap(api.get("/api/subscriptions")),
  createSub: (p: object) => unwrap(api.post("/api/subscriptions", p)),
  updateSub: (id: number, p: object) => unwrap(api.patch(`/api/subscriptions/${id}`, p)),
  deleteSub: (id: number) => unwrap(api.delete(`/api/subscriptions/${id}`)),
  debts: () => unwrap(api.get("/api/debts")),
  createDebt: (p: object) => unwrap(api.post("/api/debts", p)),
  payDebt: (id: number, p: object) => unwrap(api.post(`/api/debts/${id}/payments`, p)),
  deleteDebt: (id: number) => unwrap(api.delete(`/api/debts/${id}`)),
  payoff: (method: string, extra = 0) => unwrap(api.get(`/api/debts/payoff?method=${method}&extra=${extra}`)),
  netWorth: () => unwrap(api.get("/api/net-worth")),
  createAsset: (p: object) => unwrap(api.post("/api/assets", p)),
  deleteAsset: (id: number) => unwrap(api.delete(`/api/assets/${id}`)),
  createLiability: (p: object) => unwrap(api.post("/api/liabilities", p)),
  deleteLiability: (id: number) => unwrap(api.delete(`/api/liabilities/${id}`)),
  analytics: (period: string) => unwrap(api.get(`/api/analytics?period=${period}`)),
  forecast: (days: number) => unwrap(api.get(`/api/forecast?days=${days}`)),
  insights: () => unwrap(api.get("/api/insights")),
  search: (q: string) => unwrap(api.get(`/api/search?q=${encodeURIComponent(q)}`)),
  calendar: (year: number, month: number) => unwrap(api.get(`/api/calendar?year=${year}&month=${month}`)),
  notifications: () => unwrap(api.get("/api/notifications")),
  readNotif: (id: number) => unwrap(api.post(`/api/notifications/${id}/read`)),
  readAllNotifs: () => unwrap(api.post("/api/notifications/read-all")),
  backup: () => unwrap(api.get("/api/backup")),
  restore: (backup: object, replace: boolean) => unwrap(api.post("/api/restore", { backup, replace })),
  importPreview: (p: object) => unwrap(api.post("/api/import/preview", p)),
  importCommit: (p: object) => unwrap(api.post("/api/import/commit", p)),
};

export function exportUrl(kind: string) {
  const token = localStorage.getItem("ledgerly_token");
  const base = import.meta.env.VITE_API_URL || "";
  return `${base}/api/export/${kind}?token=${token}`;
}
